name: ServerGuide
version: 3.0.0-RELEASE
api: ["3.0.0-ALPHA9", "3.0.0-ALPHA10", "3.0.0-ALPHA11", "3.0.0-ALPHA12"]
main: ServerGuide\ServerGuide
author: Az928, edited by VMPE Development team
description: "The advanced server info plugin!"
